# Generated by Django 3.2 on 2021-12-02 16:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(default='', max_length=50)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 12, 2, 19, 46, 47, 863634, tzinfo=utc), null=True)),
                ('created_by', models.CharField(default='Rohit', max_length=50, null=True)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2021, 12, 2, 19, 46, 47, 863634, tzinfo=utc), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='', max_length=50)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 12, 2, 19, 46, 47, 864634, tzinfo=utc), null=True)),
                ('created_by', models.CharField(default='', max_length=70)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2021, 12, 2, 19, 46, 47, 864634, tzinfo=utc), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
