# Generated by Django 3.2 on 2021-12-03 13:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(default='YYYY-MM-DD HH:MM[:ss[.uuuuuu]][TZ]', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_by',
            field=models.CharField(default='Rohit', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 3, 16, 4, 29, 601451, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_by',
            field=models.CharField(default='Ganesh', max_length=70),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 3, 16, 4, 29, 601451, tzinfo=utc), null=True),
        ),
    ]
